version: '3.8'

services:
  # Frontend React application
  frontend:
    build:
      context: ./frontend
      dockerfile: ../infrastructure/docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000/api

  # Backend Express API
  backend:
    build:
      context: ./backend
      dockerfile: ../infrastructure/docker/Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo
      - redis
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/radiox
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=dev_jwt_secret
      - JWT_EXPIRES_IN=7d

  # Processing service for audio conversion
  processing:
    build:
      context: ./processing
      dockerfile: ../infrastructure/docker/Dockerfile.backend
    volumes:
      - ./processing:/app
      - /app/node_modules
    depends_on:
      - mongo
      - redis
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/radiox
      - REDIS_URL=redis://redis:6379

  # MongoDB database
  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=radiox

  # Redis for caching and job queues
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # MongoDB admin interface
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password

  # Redis admin interface
  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8082:8081"
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379

volumes:
  mongo-data:
  redis-data:
